services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${DB_PGA_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PGA_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${DB_PGA_PORT}:80"
    depends_on:
      - postgres
volumes:
  pgdata:
  pgadmin-data:
