"""create runs and measurements

Revision ID: 66ede9f08aa2
Revises: 
Create Date: 2025-10-13 15:48:02.736400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ede9f08aa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    last_run = op.create_table('last_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_last_run_id'), 'last_run', ['id'], unique=False)
    op.bulk_insert(
        last_run,
        [{'last_run': 0}],
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('measure_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('t205', sa.Float(), nullable=False),
    sa.Column('t206', sa.Float(), nullable=False),
    sa.Column('t207', sa.Float(), nullable=False),
    sa.Column('t208', sa.Float(), nullable=False),
    sa.Column('t209', sa.Float(), nullable=False),
    sa.Column('t210', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_index(op.f('ix_last_run_id'), table_name='last_run')
    op.drop_table('last_run')
    # ### end Alembic commands ###
